search_keywords:
  - data analyst
  - bi developer
  - data visualization
  - business intelligence

visa_keywords:
  - visa sponsorship
  - relocation support
  - work permit
  - sponsorship available
  - we offer relocation
  - relocation assistance
  - eu work permit support
