search_keywords:
  - data analyst
  - bi developer
  - data visualization
  - business intelligence

visa_keywords:
  - visa sponsorship
  - relocation support
  - work permit
  - sponsorship available
  - we offer relocation
  - relocation assistance
  - eu work permit support

locations:
  - netherlands
  - germany
  - poland
  - italy

telegram:
  bot_token: "7616042675:AAGf10TxZoIBLTUoBu4SecHl-aMuVFU5JiI"
  chat_id: "7991654645"

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender_email: "kosegamze97@gmail.com"
  sender_password: "udjabjyrplxdikpa"
  receiver_email: "kosegamze97@gmail.com"
