telegram:
  bot_token: "7616042675:AAGf10TxZoIBLTUoBu4SecHl-aMuVFU5JiI"
  chat_id: "7991654645"

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender_email: "kosegamze97@gmail.com"
  sender_password: "udjabjyrplxdikpa"
  receiver_email: "kosegamze97@gmail.com"
