name: Daily Job Scraper  

on:
  schedule:
    - cron: "0 8 * * *"  # Triggers every day at 08:00 UTC (11:00 Turkey time)

jobs:
  run-scraper:  # Job name 
    runs-on: ubuntu-latest  # Uses GitHub's Ubuntu virtual machine

    steps:
      - name: Checkout the repository  # Step 1: Pulls your repo code
        uses: actions/checkout@v4

      - name: Set up Python 3.11 
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run the bot script  
        run: python job_bot.py
