name: Daily Job Scraper

on:
  schedule:
    - cron: "0 8 * * *"  # Runs every day at 08:00 UTC (11:00 Turkey)
  workflow_dispatch:      # Allows manual run from GitHub Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job bot
        run: python job_bot.py
